# Numpy

In [2]:
import numpy as np

In [4]:
list1=[1,2,3,4]
list2=[2,2,4,5]
print(np.array(list1))

[1 2 3 4]


In [5]:
arr1=np.array(list1)
arr1

array([1, 2, 3, 4])

In [6]:
arr2=np.array(list2)
arr2

array([2, 2, 4, 5])

In [9]:
sum1=arr1+arr2
sum1

array([3, 4, 7, 9])

In [10]:
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
list1      list       n=4
list2      list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [12]:
data2=[[1,2,3,4],[5,6,7,8]]
arr3=np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr3.ndim

2

In [14]:
arr3.dtype

dtype('int32')

In [15]:
arr3.shape #how many rows & cols

(2, 4)

In [4]:
import numpy as np

In [6]:
data2=[[1,2,3,4],[5,6,7,8]]
arr3=np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr4=np.array(data2,dtype=float)
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [9]:
arr4.dtype

dtype('float64')

In [10]:
# UI implies string data type

In [11]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [13]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
arr7=np.arange(4,20)
arr7

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr8=np.arange(4,20,2)
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr9=arr8.reshape(4,2)
arr9

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [19]:
arr11=np.linspace(1,30,5)  # linspace divides the list to eqaual intervals
arr11

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [20]:
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
arr[5:12] # 5 and 12 indicates the index

array([10, 11, 12, 13, 14, 15, 16])

In [22]:
arr[5]

10

In [23]:
arr[5:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
arr[:5]

array([5, 6, 7, 8, 9])

In [25]:
arr[[1,3,5]] # to print multiple values give two brackets

array([ 6,  8, 10])

In [26]:
arr2=np.array([[-7,5,-2,4],[5,6,-9,3],[10,-13,-3,5]])
arr2

array([[ -7,   5,  -2,   4],
       [  5,   6,  -9,   3],
       [ 10, -13,  -3,   5]])

In [27]:
arr2[0]

array([-7,  5, -2,  4])

In [28]:
arr2[[0,1]] 

array([[-7,  5, -2,  4],
       [ 5,  6, -9,  3]])

In [29]:
arr2[:,1]  # col with index 1

array([  5,   6, -13])

In [32]:
arr3=np.arange(10,82,2)
arr3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [33]:
len(arr3)

36

In [38]:
arr3=arr3.reshape(6,6)
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [39]:
arr3[:,[0,2]]  # col with index 0 and 2

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [40]:
arr3[:,0:2]   # col with index from 0 to 1

array([[10, 12],
       [22, 24],
       [34, 36],
       [46, 48],
       [58, 60],
       [70, 72]])

In [41]:
arr3[:2,:]  # row with index from 0 to 1 

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [42]:
arr3[:2]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [47]:
arr3[0:2]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32]])

In [48]:
arr4=np.array([38,40,42,50])

In [49]:
arr4.sum()

170

In [50]:
np.sum(arr4)

170

In [51]:
arr4.mean()

42.5

In [52]:
np.median(arr4)  # arr4.median() will show an error

41.0

In [54]:
arr4=arr4.reshape(2,2)
arr4

array([[38, 40],
       [42, 50]])

In [55]:
arr4.sum()

170

In [56]:
arr4.sum(1) # sum of rows

array([78, 92])

In [57]:
arr4.sum(0) # sum of cols

array([80, 90])

In [58]:
arr3+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [59]:
arr3/5

array([[ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ],
       [ 4.4,  4.8,  5.2,  5.6,  6. ,  6.4],
       [ 6.8,  7.2,  7.6,  8. ,  8.4,  8.8],
       [ 9.2,  9.6, 10. , 10.4, 10.8, 11.2],
       [11.6, 12. , 12.4, 12.8, 13.2, 13.6],
       [14. , 14.4, 14.8, 15.2, 15.6, 16. ]])

In [62]:
arr3[5]=-9   # replace all elements in index 5 as -9
arr3

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [64]:
arr3=np.abs(arr3)   # gives absolute values 
arr3 

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [67]:
np.sqrt(arr3)


array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [68]:
type(arr3)

numpy.ndarray

In [69]:
np.zeros((5,5))  # converts all elements to zero. need 2 brackets

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.eye(5,5)  # gives identity matrix. note only one bracket

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
A=np.arange(8).reshape(2,4)
B=np.arange(8).reshape(4,2)
A


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [76]:
A.dot(B) # dot product (matrix multiplication)

array([[28, 34],
       [76, 98]])

In [77]:
arr3.T  # gives transpose of the matrix

array([[10, 22, 34, 46, 58,  9],
       [12, 24, 36, 48, 60,  9],
       [14, 26, 38, 50, 62,  9],
       [16, 28, 40, 52, 64,  9],
       [18, 30, 42, 54, 66,  9],
       [20, 32, 44, 56, 68,  9]])